django_inline_formset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls", namespace="products")),
    path('', include("statistiche.urls", namespace="statistiche")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import (
    ProductList, ProductCreate, ProductUpdate,
    delete_image, delete_variant
)

app_name = 'products'  # 3rd

urlpatterns = [
    
    path('create/', ProductCreate.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdate.as_view(), name='update_product'),
    path('delete-image/<int:pk>/', delete_image, name='delete_image'),
    path('delete-variant/<int:pk>/', delete_variant, name='delete_variant'),
]

statistiche/urls.py
from django.urls import path

from .views import (
    GiornalieroList, GiornalieroCreate, GiornalieroUpdate,
    delete_image, delete_dettaglio
)

app_name = 'statistiche'

urlpatterns = [
    path('', GiornalieroList.as_view(), name='list_giornaliero'),
    path('statistiche/create/', GiornalieroCreate.as_view(), name='create_giornaliero'),
    path('statistiche/update/<int:pk>/', GiornalieroUpdate.as_view(), name='update_giornaliero'),
    path('delete-image/<int:pk>/', delete_image, name='delete_image'),
    path('delete-dettaglio/<int:pk>/', delete_dettaglio, name='delete_dettaglio'),
]

statistiche/models.py
from django.db import models

class descMovimenti(models.Model):
    descrizione = models.CharField(max_length=100, null=True)
    
    def __str__(self):
        return self.descrizione

class Giornaliero(models.Model):
    data = models.DateField()
    descrizione = models.CharField(max_length=100, null=True, blank=True)
    totaleCassa = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    incassoPresunto = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    differenza = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    def __str__(self):
        return self.data, self.descrizione
    

class Image(models.Model):
    giornaliero = models.ForeignKey(Giornaliero, on_delete=models.CASCADE, null=True)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.giornaliero.data
    

class Dettagli(models.Model):
    tipoMovimento = descMovimenti.objects.all()
    '''tipoMovimento = ( 
        ('TABACCHI', 'TABACCHI'), 
        ('LOTTO', 'LOTTO'),
        ('ART. TABACCHERIA', 'ART. TABACCHERIA'),
        ('SISAL', 'SISAL'),
        ('GRATTA E VINCI', 'GRATTA E VINCI'),
        ('ALTRE USCITE', 'ALTRE USCITE'),
        ('PASTIGLIAGGI', 'PASTIGLIAGGI'),
        ('VALORI BOLLATI', 'VALORI BOLLATI'),
    ) ''' 
    giornaliero = models.ForeignKey(Giornaliero, on_delete=models.CASCADE)
    movimento = models.ForeignKey(descMovimenti, on_delete=models.CASCADE)
    '''movimento = models.CharField(max_length=100, choices=tipoMovimento)'''
    entrata = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    uscita = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    def __str__(self):
        return self.giornaliero.data
    

statistiche/forms.py
from django import forms
from django.forms import inlineformset_factory
from datetime import datetime


from .models import (
    Giornaliero, Image, Dettagli, descMovimenti
)


class GiornalieroForm(forms.ModelForm):

    totaleCassa = forms.DecimalField(label='Totale Cassa', widget=forms.NumberInput(attrs={'step': '0.01', 'class': 'form-control', 'id': 'g_totaleCassa', 'readonly': 'readonly' }))
    descrizione = forms.CharField(label='Esito controllo', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'descrizioneId', 'readonly': 'readonly' }))

    class Meta: 
        model = Giornaliero
        fields = ['data', 'descrizione', 'totaleCassa', 'incassoPresunto']

        
        widgets = {
            'data': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                       'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'date'
                },
            ),
            'incassoPresunto': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'id': 'g_incassoPresunto',
                }
            ),
        }

        


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = '__all__'


class DettagliForm(forms.ModelForm):

    '''tipoMovimento = ( 
        ('TABACCHI', 'TABACCHI'), 
        ('LOTTO', 'LOTTO'),
        ('ART. TABACCHERIA', 'ART. TABACCHERIA'),
        ('SISAL', 'SISAL'),
        ('GRATTA E VINCI', 'GRATTA E VINCI'),
        ('ALTRE USCITE', 'ALTRE USCITE'),
        ('PASTIGLIAGGI', 'PASTIGLIAGGI'),
        ('VALORI BOLLATI', 'VALORI BOLLATI'),
    ) 
    movimento = forms.ChoiceField(
                    choices=tipoMovimento,
                    widget=forms.Select(attrs={'class': 'form-control'})                                  
                )'''
    movimento = forms.ModelChoiceField(queryset=descMovimenti.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))

    class Meta:
        model = Dettagli
        fields = '__all__'
        widgets = {
            
            'entrata': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'step': 0.1,
                    'name': "rigo",
                    'onchange': "calcolaTotale(this);",
                }
            ),
            'uscita': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'step': 0.1,
                    'onchange': "calcolaTotale(this);",
                    }
            ),
        }


DettagliFormSet = inlineformset_factory(
    Giornaliero, Dettagli, form=DettagliForm,
    extra=1, can_delete=False,
    can_delete_extra=False
)
ImageFormSet = inlineformset_factory(
    Giornaliero, Image, form=ImageForm,
    extra=1, can_delete=True,
    can_delete_extra=False
)

statistiche/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import (CreateView, UpdateView)
from django.db.models import Sum


from .forms import (
    GiornalieroForm, DettagliFormSet, ImageFormSet
)
from .models import (
    Image,
    Dettagli,
    Giornaliero
)


class GiornalieroInline():
    form_class = GiornalieroForm
    model = Giornaliero
    template_name = "statistiche/giornaliero_aggiorna_crea.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()

        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('statistiche:list_giornaliero')


    def formset_dettagli_valid(self, formset):
        dettagli = formset.save(commit=False)  
        for obj in formset.deleted_objects:
            obj.delete() 
        for dettaglio in dettagli:
            dettaglio.giornaliero = self.object
            dettaglio.save() #In questo punto salviamo i dati finali ed usciamo dalla maschera di inserimento 


    def formset_images_valid(self, formset):
        images = formset.save(commit=False)  
        for obj in formset.deleted_objects:
            obj.delete()
        for image in images:
            image.product = self.object
            image.save()
                


class GiornalieroCreate(GiornalieroInline, CreateView): 

    def get_context_data(self, **kwargs):
        ctx = super(GiornalieroCreate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'dettagli': DettagliFormSet(prefix='dettagli'),
                'images': ImageFormSet(prefix='images'),
            }
        else:
            return {
                'dettagli': DettagliFormSet(self.request.POST or None, self.request.FILES or None, prefix='dettagli'),
                'images': ImageFormSet(self.request.POST or None, self.request.FILES or None, prefix='images'),
            }


class GiornalieroUpdate(GiornalieroInline, UpdateView):
    
    def get_context_data(self, **kwargs):
        ctx = super(GiornalieroUpdate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        return {
            'dettagli': DettagliFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='dettagli'),
            'images': ImageFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='images'),
        }
    

def delete_image(request, pk):
    try:
        image = Image.objects.get(id=pk)
    except Image.DoesNotExist:
        messages.success(request, 'Object Does not exit')
        return redirect('statistiche:update_giornaliero', pk=image.giornaliero.id)

    image.delete()
    messages.success(request, 'Image deleted successfully')
    return redirect('statistiche:update_giornaliero', pk=image.giornaliero.id)


def delete_dettaglio(request, pk):
    try:
        dettagli = Dettagli.objects.get(id=pk)
    except Dettagli.DoesNotExist:
        messages.success(request, 'Object Does not exit')
        return redirect('statistiche:update_giornaliero', pk=dettagli.giornaliero.id)

    dettagli.delete()
    messages.success(request,'Variant deleted successfully')
    return redirect('statistiche:update_giornaliero', pk=dettagli.giornaliero.id)


class GiornalieroList(ListView):
    model = Giornaliero
    template_name = "statistiche/list_giornaliero.html"
    context_object_name = "statistiche"

statistiche/templates/statistiche/giornaliero_aggiorna_crea.html
{% extends "base.html" %}

{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="giornaliero_form">
    {% csrf_token %}
    <!-- main form start --- in our case product form -->
    <div class="card" style="max-width: 100%;">
        <div class="card-header">
            <h4 class="card-title">Chiusura giornaliera</h4>
        </div>
        {% for field in form %}
            <div class="card-body p-2">
                
            {% if field.name == "incassoPresunto" %}
                <label for="{{ form.id_for_label }}">Incasso riportato sul terminale</label>
                <div class="input-group mb-0">
                    {{field}}
                    <div class="input-group-append">
                      <button class="btn btn-outline-secondary" type="button" onclick="calcolaTotale(this)">Ricalcola</button>
                    </div>
                </div>

            {% else %}
                 <label for="{{ field.id_for_label }}">{{ field.label }}</label>       
                {{field}}
            {% endif %}       
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
                
            </div>
        {% endfor %}
    </div>

    {% with named_formsets.images as formset %}  
        {{ formset.management_form }}
        <script type="text/html" id="images-template">   // id="inlineformsetname-template"
            <tr id="images-__prefix__" class= hide_all>  // id="inlineformsetname-__prefix__"
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}
            
                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>

        <div class="table-responsive card mt-4" style="max-width: 100%;">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Aggiungi immagini report</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                    <th>Immagine <span style="color: red;" class="required">*</span></th>
                    <th>Seleziona?</th>
                    <th>Elimina</th>
                </thead>
                <tbody id="item-images">  <!-- id="item-inlineformsetname" -->
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="images-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </td>
                            {% endfor %}
                            <!-- delete code -->
                            {% if formss.instance.pk %}
                                <td>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}">
                                        Delete
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'statistiche:delete_image' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>            
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-image-button" class="btn btn-secondary add-images">Add More</a> <!-- id="add-inlineformsetname-button" -->
        </div>
    {% endwith %}
 
    <!-- EXPLAINING with named_formsets.variants as formset -->
    <!-- Note: named_formsets is used in get_context_data function in views.py -->
    <!-- Note: here variants is our VariantFormSet name, used in get_named_formsets function in views.py -->
    {% with named_formsets.dettagli as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="dettagli-template">  // id="inlineformsetname-template"
            <tr id="dettagli-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}
            
                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>

        <div class="table-responsive card mt-4" style="max-width: 100%;">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Aggiungi dettagli incasso</h4>
            </div>
            <table class="table card-header">
                <thead class="text-secondary">
                    <th>Tipo movimento</th>
                    <th>Entrata</th>
                    <th>Uscita</th>
                    <th>Elimina</th>
                </thead>
                <tbody id="item-dettagli"> 
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="dettagli-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                    
                                    {% comment %} {{ field.DELETE }} {% endcomment %}
                                </td>
                            {% endfor %}
                            {% comment %} for delete {% endcomment %}
                            {% if formss.instance.pk %}
                                <td>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}">
                                        Elimina
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'statistiche:delete_dettaglio' formss.instance.pk %}" type="button" class="btn btn-primary">Conferma, Elimina</a>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>            
                            {% endif %}
                        </tr>                     
                    {% endfor %}
                </tbody>
            </table>        
            <a href="#" id="add-dettagli-button" class="btn btn-secondary add-dettagli">Aggiungi rigo</a> <!-- id="add-inlineformsetname-button" -->
        </div> 

        {% endwith %}
        
        <div class="form-group">
            <button type="submit" class="btn btn-secondary btn-block">Salva ed Esci</button>
        </div>
</form>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    $(document).ready(function() {
        // when user clicks add more btn of images
      $('.add-images').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-images').children().length;
          var tmplMarkup = $('#images-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-images').append(compiledTmpl);
  
          // update form count
          $('#id_images-TOTAL_FORMS').attr('value', count+1);
      });
  });

  $(document).ready(function() {
    // when user clicks add more btn of variants
      $('.add-dettagli').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-dettagli').children().length;
          var tmplMarkup = $('#dettagli-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-dettagli').append(compiledTmpl);
  
          // update form count
          $('#id_dettagli-TOTAL_FORMS').attr('value', count+1);
      });
  });
  

  function calcolaTotale(v){
    var sum=0;
    //var index = index + ($(v).parent().parent().index());
    var righi = $('#id_dettagli-TOTAL_FORMS').attr('value');

    for (let index = 0; index < righi; index++){
        var valore = document.getElementById('id_dettagli-'+index+'-entrata').value;
        sum = +(sum)+ +(valore);
    }
    var totEntrate = sum;
    sum = 0;
    for (let index = 0; index < righi; index++){
        var valore = document.getElementById('id_dettagli-'+index+'-uscita').value;
        sum = +(sum)+ +(valore);
    }
    var totUscite = sum;
    var totCassa = totEntrate - totUscite;
    var presunto = document.getElementById('g_incassoPresunto').value;
    var differenza = totCassa - presunto;

    //document.getElementById('totEntrate').value = totEntrate.toFixed(2);
    //document.getElementById('totUscite').value = totUscite.toFixed(2);
    document.getElementById('g_totaleCassa').value = totCassa.toFixed(2);
    //document.getElementById('g_differenza').value = differenza.toFixed(2);

    if (differenza > 0) {
        document.getElementById('descrizioneId').value = "Disavanzo di +" + differenza.toFixed(2)+"€";

    } else {
        document.getElementById('descrizioneId').value = "Disavanzo di " + differenza.toFixed(2)+"€";
    }
   
  }


</script>
        
{% endblock content %}

statistiche/templates/statistiche/list_giornaliero.html
<!-- product_list.html -->
{% extends "base.html" %}


{% block content %}
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Elenco chiusure precedenti</h4>
            <a href="{% url 'statistiche:create_giornaliero' %}">Aggiungi chiusura</a>
        </div>
        <ul>
            {% for i in statistiche %}
                <li class="card-body">{{ i.data }}: {{ i.descrizione }} | <a href="{% url 'statistiche:update_giornaliero' i.id %}">Modifica</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}